### ISSUE TITLE
Properly track ontology versions

### ISSUE THREAD

**Issue by SamuelFriedman** [hubmapconsortium/hubmap-ontology#5]
Official releases of ontologies should be released via [GitHub Releases](https://github.com/hubmapconsortium/hubmap-ontology/releases). Staging and production releases should be made available in `staging` and `gh-pages` branches along with the continuous integration results.

**Comment by jpsluka** [comment]
Need to specify the "master" version of the ontology and the language it is in.
I prefer that the ontologies all be in OWL.
Regardless of the language, there are multiple reifications of the ontologies (.owl, .rdf, ...) and a particular one should be declared as the master document.
Perhaps create a subfolder for "other_reifications".

**Comment by SamuelFriedman** [comment]
We should use code that lets us output via command line and owlapi to different formats:
https://github.com/ghxiao/owl-toolkit

**Comment by SamuelFriedman** [comment]
@jpsluka We are making RDF/OWL be the "master" file format. 

@bherr2 Can you confirm the following branch structure?
* `master` (Stable code, but not yet released)
* `dev` (Unstable code)
* `staging` (Stable code, released?)
* `gh-pages` (Documentation?)

**Comment by bherr2** [comment]
* `master` (Stable, most up-to-date code, but not necessarily released)
* `develop` (Unstable, in development code) -- Every one of our projects calls it `develop`, not `dev` just our preference.

We only need `staging` and `gh-pages` IF we are generating things using Continuous Integration and pushing them automatically (ie running tests, generating documentation, compiling the rdf and different reifications, etc). At this stage, it doesn't seem likely that we'll have that. If we can get that far, here's how it would work:

Whenever a commit is pushed to `develop` this would be picked up by Travis CI. It would then run the doc generator, run any tests we have setup, and compile the rdf + reifications. If successful, it'd push the generated files to `staging`. Then netlify.com would see the new push to `staging` and host that branch as a website.

Whenever a commit is pushed to `master` the same process would be kicked off, but instead pushed to `gh-pages` which is then picked up and hosted by github.io.

So:
* `staging` (Built documentation and ontologies from `develop`)
* `gh-pages` (Built documentation and ontologies from `master`)

When a tag is pushed, a similar process is spun off, but instead of pushing the results to a branch, its pushed to a tag which becomes part of the release.

**Comment by bherr2** [comment]
I can help setup Travis CI, but the only way that'll work is if the documentation and ontology generation workflow can actually be run on the command line.

**Comment by SamuelFriedman** [comment]
I agree that we're not that far yet for the CI, but I'm working on restructuring the code to be able to do this. So I think we should push this to the next release possibly and just rename the `dev` branch to `develop`.
